# Funding configuration for IPv6-Only Tools project

github: # GitHub Sponsors
  - Hyperpolymath

patreon: # Patreon

open_collective: # Open Collective

ko_fi: # Ko-fi

tidelift: # Tidelift

community_bridge: # Community Bridge

liberapay: # Liberapay

issuehunt: # IssueHunt

otechie: # Otechie

lfx_crowdfunding: # LFX Crowdfunding (formerly CommunityBridge)

custom: # Custom URLs
  - https://buymeacoffee.com/ipv6tools
